---
title: "R 期中競賽 第三組"
output:
  html_document:
    df_print: paged
---

```{r results='hide', message=FALSE, warning=FALSE, echo=F}
# 這些程式碼設定網頁的格式，並安裝、載入一些基本的套件，請大家不要去改動
rm(list=ls(all=T))
knitr::opts_chunk$set(comment = NA)
knitr::opts_knit$set(global.par = TRUE)
par(cex=0.8)
options(scipen=20, digits=5, width=80)
if(!require(pacman)) install.packages("pacman")
```

```{r results='hide', message=FALSE, warning=FALSE, echo=F}
packages = c("dplyr","stringr","readr","ggplot2","scales","mapdata","maps","Imap","factoextra","lubridate")

existing = as.character(installed.packages()[,1])
for (pkg in packages[!(packages %in% existing)])install.packages(pkg)

sapply(packages,library, character.only = T)
```

###共同區域###

#Loading multiple .csv files as separate data frames
```{r}
getwd()
folder <- "data/"
file_list <- list.files(path = folder, pattern = "*.csv")
```

#Read in each .csv file 
```{r}
for (i in 1:length(file_list)){
  assign(file_list[i],
         read.csv(paste(folder,file_list[i],sep=''),stringsAsFactors = F)
  )}
```

#Rename data
```{r}
geo <- olist_geolocation_dataset.csv
orders <- olist_orders_dataset.csv
cust <- olist_customers_dataset.csv
sellers <- olist_sellers_dataset.csv
products <- olist_products_dataset.csv
orderitems <- olist_order_items_dataset.csv
payments <- olist_order_payments_dataset.csv
nametrans <- product_category_name_translation.csv
reviews <- olist_order_reviews_dataset.csv
closed <- olist_closed_deals_dataset.csv
marketing <- olist_marketing_qualified_leads_dataset.csv
```


################################################
################以下王欣部分####################
################################################

###前處理

#1 地理資料整理
```{r}
geo$geolocation_lat<-round(geo$geolocation_lat,3)
geo$geolocation_lng<-round(geo$geolocation_lng,3)

selllocation<-geo %>% group_by(geolocation_city) %>% summarise(selllat = max(geolocation_lat),selllng=max(geolocation_lng))
custlocation<-geo %>% group_by(geolocation_city) %>% summarise(custlat = max(geolocation_lat),custlng=max(geolocation_lng))
```

#2 時間資料處理
```{r}
orders$order_approved_at<-strptime(orders$order_approved_at,format="%Y-%m-%d %H:%M:%S")
orders$order_purchase_timestamp<-strptime(orders$order_purchase_timestamp,format="%Y-%m-%d %H:%M:%S")
orders$order_delivered_carrier_date<-strptime(orders$order_delivered_carrier_date,format="%Y-%m-%d %H:%M:%S")
orders$order_delivered_customer_date<-strptime(orders$order_delivered_customer_date,format="%Y-%m-%d %H:%M:%S")
orders$order_estimated_delivery_date<-strptime(orders$order_estimated_delivery_date,format="%Y-%m-%d %H:%M:%S")

table(orders$order_status)
orderitems$shipping_limit_date<-strptime(orderitems$shipping_limit_date,format="%Y-%m-%d %H:%M:%S")
```

#3 把各個資料合併
```{r}
M_1 <- merge(orderitems,sellers,by.x="seller_id",by.y="seller_id")
M_2 <- merge(orders,cust,by.x="customer_id",by.y="customer_id")
M_3 <- merge(M_2,M_1,by="order_id")
M_4 <- merge(M_3,products,by="product_id")
M_5 <- merge(M_4,payments,by="order_id")
M_6 <- merge(M_5,selllocation,by.x="seller_city",by.y="geolocation_city")
M_7 <- merge(M_6,custlocation,by.x="customer_city",by.y="geolocation_city")

colnames(nametrans) <- c("product_category_name","product_category_name_english")

```

#4 計算買賣家之間的距離
```{r}
dist_list <- list()

for (i in 1:nrow(M_7)) {
  
  dist_list[[i]] <- gdist(lon.1 = M_7$selllng[i], 
                          lat.1 = M_7$selllat[i], 
                          lon.2 = M_7$custlng[i], 
                          lat.2 = M_7$custlat[i], 
                          units="miles")
  
}
M_7$distbtwn<-as.integer(dist_list)
M_8<-merge(M_7,nametrans,by="product_category_name")
```

#5 置入巴西地理資料
```{r}
Brazil<-map_data("world") %>% filter(region=="Brazil")

#排除界外外的資料
M_8 = M_8[M_8$selllat <= 5.27438888,]
M_8 = M_8[M_8$custlat <= 5.27438888,]
```

#畫出賣家所在地
```{r}
ggplot() +
  geom_polygon(data = Brazil, aes(x=long, y = lat, group = group), fill="gray")+
  geom_point(data= M_8,aes(x=selllng,y=selllat,color=seller_state),size=0.2)

sum(M_8$seller_state=="BA" )
```

#畫出買家所在地
```{r}
ggplot() +
  geom_polygon(data = Brazil, aes(x=long, y = lat, group = group), fill="gray")+
  geom_point(data= M_8,aes(x=custlng,y=custlat,color=customer_state),size=0.2)
```

#各產品類別銷售情況及所在地
```{r}
ggplot() +
  geom_bar(data= M_8,aes(product_category_name_english,fill=seller_state),width=1)+ coord_flip()
```

#賣家所在地數量
```{r}
ggplot() +
  geom_bar(data= M_8,aes(seller_state,fill=seller_state),width=1)
```
#6 找出前100大賣家
```{r}
seller_TOP100 <-
  M_8 %>% group_by(seller_id,product_category_name_english) %>% summarise(
  mount = sum(price),
  num = n()) %>% arrange(desc(num)) %>% head(100)

seller_TOP100_2 <- merge(seller_TOP100,closed[,c(1,2,6,8,9,12)],by="seller_id",all.x = T)

marketingdata <- merge(closed[,c(1,2,6,8,9,12)],marketing[,c(1,4)],by = "mql_id")
 
M_9 <-  merge(M_8,marketingdata,by = "seller_id")
```

#分析
```{r}
A_1 <- M_9 %>% group_by(lead_behaviour_profile,business_segment) %>% summarise(
  n_business = n(),
  mount = sum(price),
  every_mount = mount/n_business
  )  %>% arrange(desc(lead_behaviour_profile))
   
table(A_1$lead_behaviour_profile) 
```
```{r}
ggplot() +
  geom_polygon(data = Brazil, aes(x=long, y = lat, group = group), fill="gray")+
  geom_point(data= M_9,aes(x=custlng,y=custlat,color=lead_behaviour_profile),size=0.2)

ggplot() +
  geom_polygon(data = Brazil, aes(x=long, y = lat, group = group), fill="gray")+
  geom_point(data= M_9[M_9$lead_behaviour_profile=="wolf",],aes(x=custlng,y=custlat,color=lead_behaviour_profile),size=0.2)
```
#7 找對評分的重要變數
```{r}
M_9 %>% colnames() #2:4,9:11,15,17,19:20,22,24,25,32,38
score <- M_9[,c(5,10:12,16,17,19,20,22,24,25,32,38)] %>% group_by(order_id) %>% summarise(
  ship13 = mean(order_delivered_customer_date-order_approved_at),
  ship12 = mean(order_delivered_carrier_date-order_approved_at),
  ship23 = mean(order_delivered_customer_date-order_delivered_carrier_date),
  ship_ratio = mean(freight_value/price),
  description = sum(product_description_lenght)/max(order_item_id),
  photo_num = sum(product_photos_qty)/max(order_item_id),
  pay_installment = sum(payment_installments)/max(order_item_id),
  dist = sum(distbtwn)/max(order_item_id),
  customer_state = head(customer_state,1),
  seller_state = head(seller_state,1)
)  

reviews2 <- reviews %>% group_by(order_id) %>% summarise(
  score = mean(review_score)
)
```

```{r}
score_lm<-merge(score,reviews2,by="order_id")
colnames(score)
model <- lm(score ~ . ,data = score_lm[,c(2:9,12)])
summary(model)
```

```{r}
table( unique(M_8[, c(16,39)])$seller_id ) %>% table 
unique(M_8[,16])%>% length()
```

################################################
################以下張延瑋部分##################
################################################

################################################
################以下黃柏勳部分##################
################################################

```{r}
#尋找出銷售最高的產品
bs_olist.p <- olist_products_dataset.csv ##32,951 consumers 
table(bs_olist.p$product_category_name) %>% sort(decreasing = TRUE) ##消費最多是 cama_mesa_banho 3029
 
#
v <- mutate(bs_olist.p, product_volume= product_length_cm*product_height_cm*product_width_cm)
ggplot(v, aes(product_photos_qty, product_name_lenght))+ geom_point()
ggplot(v, aes(product_volume))+ geom_bar()
table(v$product_photos_qty) ##1 photo
table(v$product_category_name, v$product_photos_qty)
ggplot(v,aes(product_name_lenght))+ geom_bar()  ##左尾分布 集中在接近60
ggplot(v,aes(product_description_lenght))+ geom_bar() ##右尾分布 集中在0~1000
ggplot(v,aes(product_volume))+ geom_histogram(binwidth = 1500)
by_name <- group_by(v,product_category_name) %>% summarise(avg = mean(product_volume)) %>% as.data.frame() ##貨物平均體積
by_name <- by_name[-1,]
product_category_name_translation.csv$product_category_name<-product_category_name_translation.csv$嚜穆roduct_category_name
m <- merge(by_name,product_category_name_translation.csv,all = F)
m <- m[,-3]  ##貨物種類-平均體積
```

```{r}
##整理消費者購買月份

library(data.table)

ts = as.POSIXct(as.character(olist_orders_dataset.csv$order_purchase_timestamp) , format="%Y-%m-%d %T")

ts.bym <- cut(ts, breaks = "month")
dfts <- data.frame(ts,ts.bym)
table(dfts$ts.bym)
ggplot(dfts, aes(ts.bym),las=1)+ geom_bar() ##最多銷售月份為2018-1-1


##每日尖峰時段
ts.byH <- format(ts,format="%H") %>% data.frame()
ggplot(ts.byH ,aes(.))+ geom_bar()
table(ts.byH)
```


```{r}
##商品種類-月份

a <- merge(olist_orders_dataset.csv, olist_order_items_dataset.csv, by.x = "order_id")
b <- merge(a, olist_products_dataset.csv, by.x = "product_id")
c <- merge(b, product_category_name_translation.csv, by.x= "product_category_name")

D <- select(c,product_category_name_english, order_purchase_timestamp)

DD = as.POSIXct(as.character(D$order_purchase_timestamp) , format="%Y-%m-%d %T")
DD.bym <- format(DD,format="%m")
D$bym <- DD.bym
E <- filter(D, product_category_name_english=="bed_bath_table"|product_category_name_english=="health_beauty"|product_category_name_english=="sports_leisure"|product_category_name_english=="furniture_decor"|product_category_name_english=="computers_accessories"|product_category_name_english=="housewares" )

summary(D$product_category_name_english) %>% sort()

##table(D$product_category_name_english, D$bym)
ggplot(E ,aes(product_category_name_english, fill=bym))+ geom_bar() ##抓出銷售量最高的六種商品做每個月分的比例圖

ggplot(D, aes(product_category_name_english, fill=bym, width=1))+ geom_bar()+coord_flip()  ##每種商品每個月分的銷售狀況

##按照小時區分
DD.byh <- format(DD,format="%H")
D$byh <- DD.byh
##table(D$product_category_name_english, D$byh)
ggplot(D, aes(product_category_name_english, fill=byh, width=1))+ geom_bar()+coord_flip()##按照時間點的銷售量
```


```{r}
###抓出一次性購買消費者特性
Q <- group_by(olist_customers_dataset.csv, customer_unique_id) %>% summarise(nid=n())
Q <- filter(Q, nid==1) 
QQ <- olist_customers_dataset.csv
QQQ <- merge(Q,QQ, by="customer_unique_id")
W <- merge(QQQ, olist_orders_dataset.csv, by="customer_id", all=F)
WW <- merge(W,olist_order_items_dataset.csv, by="order_id", all=F)
WWW <- merge(WW, olist_products_dataset.csv, by="product_id", all=F)
WWWW <- merge(WWW,product_category_name_translation.csv, by="product_category_name", all = F)
table(WWWW$product_category_name_english) %>% sort() ##消費量最多為bed_beath
onece <- group_by(WWWW, product_category_name_english) %>% summarise(mean=mean(price), sum=sum(price))##平均消費額最多為computers與總消費最多為health_beauty
```

################################################
################以下孫嘉力部分##################
################################################
```{r}
#數據的定義會用到下面李璨宇的部分
reviews <-olist_order_reviews_dataset.csv
orderitms <- olist_order_items_dataset.csv
sellers <-  olist_sellers_dataset.csv
#A <- review of orderitems 
A<-merge(x = reviews , y = orderitems, by = "order_id")
#E <- review of sellers with order information
E<-merge(x = A , y = sellers, by = "seller_id")

library(dplyr)
library(leaflet)
library(maps)
#score: the average score of each city
score <- E %>%
group_by(seller_city) %>% 
  summarise(
  score = mean(review_score)
  ) 

#geolocation: private dataframe, with state,lon and lat of each city
geolocation <- olist_geolocation_dataset.csv
geolocation['geolocation_zip_code_prefix'] = NULL
geolocation <- geo %>% 
group_by(geolocation_city) %>% 
summarise(
  lat = mean(geolocation_lat),
  lng = mean(geolocation_lng)
  )
geolocation['state'] = geo["geolocation_state"]
geolocation['seller_city'] = geo['geolocation_city']

#merge score of cities and geo of cities so that we can use leaflet
city_score <- merge(score,geolocation,by="seller_city")
city_score_fig <- leaflet() %>% 
  addTiles()  %>%
  addCircleMarkers(
    lng     = city_score$lng,
    lat     = city_score$lat,
    label   = city_score$seller_city,
    color   = city_score$score,
    labelOptions = labelOptions(noHide = F) ,
    options = popupOptions(closeButton = FALSE)
  )

#下面畫一個每個state的評價情況
city_score %>% group_by(state) %>% summarise(
  score = mean(score)
)
```

#draw review of each state and use addPolygon to fig
```{r}
city_score %>%
group_by(state) %>%
summarise(
  score = mean(score)
)
state_score_fig <- leaflet() %>%
  addTiles() %>%
  addpPolygons()
```


################################################
################以下李璨宇部分##################
################################################
```{r}
#合併資料
m1<-merge(x = orderitems, y = reviews, by = "order_id")
m2<-merge(x = m1, y = closed, by = "seller_id")
m3<-merge(x = m1, y = sellers, by = "seller_id")
```

```{r}
#不同商品種類的平均評價分數 : air conditioning和handcrafted的平均評價最好
Q <- group_by(m2,business_segment)%>%summarize(score=mean(review_score))
arrange(Q,score)
sort(table(m2$business_segment))
```

```{r}
#運費佔價格比例與評分的關聯，圖形上看起來，運費佔比越高，消費者對商品評價越低。但運費佔比與評價的相關係數很小
m30=mutate(m3,fdividep=freight_value/price)
ggplot(m30, aes(fdividep, review_score))+  
geom_smooth(se = FALSE) 
model=lm(m30$fdivide~m30$review_score) 
summary(model)
cor(m30$fdivide,m30$review_score)
model=lm(m30$freight_value~m30$review_score) #運費高低與評價的相關係數也很小
summary(model)
cor(m30$freight_value,m30$review_score)

#不同程度的運費佔比，佔商品總數百分比。可見多達75.759%的商品，其運費佔比小於0.4
C2=mutate(orderitems,fdividep2=freight_value/price) #C2含有112650 obs.
summarise(filter(C2, fdividep2 < 0.1 ),n())/112650      
summarise(filter(filter(C2, fdividep2 < 0.2), fdividep2 >= 0.1),n())/112650  
summarise(filter(filter(C2, fdividep2 < 0.3), fdividep2 >= 0.2),n())/112650 
summarise(filter(filter(C2, fdividep2 < 0.4), fdividep2 >= 0.3),n())/112650  
summarise(filter(C2, fdividep2 >= 0.4),n())/112650      
hist(C2$fdividep2,las=2,freq=T,xlab="運費佔比",ylab="數量",main="運費佔比的數量")
```

```{r}
#直方圖 : 歷年來每個月交易數量
t=as.Date(reviews$review_creation_date)
hist(t,"month",las=2,freq=T,xlab="時間",ylab="數量",main="歷年來每個月交易數量")
#不同月分的商品獲得5分評價的比例 : 可見7、8月商品評價較高
score5<-filter(reviews, review_score ==5 )
ts5=as.Date(score5$review_creation_date)
table(format(ts5,'%m')) %>% sort()
ratio5<-table(format(ts5,'%m'))/table(format(t,'%m'))
ratio5
```

```{r}
#商品價格和評分高低的關係。從圖型來看，大約超過3000元的商品，越貴評分越高越貴的商品評分越高。但商品價格和評分高低相關係數相當低，可推測兩者並無太大關連
plot(m1$price,m1$review_score,main="", ylab="評分", xlab="價錢")
ggplot(m1, aes(price, review_score))+
geom_smooth(se = FALSE) 
model=lm(m1$price~m1$review_score) 
summary(model)
cor(A$price,A$review_score)
cor(m1$price,m1$review_score)
```


################################################
################以下劉漢慈部分##################
################################################

